### ISSUE TITLE
GeoIP2 Precision service error after site move

### ISSUE THREAD

**Issue by cdshannon** [elialgranti/geoswitch#4]
Hi Eli,

Thanks for the great plugin. I am implementing it on a Wordpress Dev, via your WP plugin (https://wordpress.org/plugins/geoswitch/) with a GeoIP2 Web service and it was (and is) working perfectly on my sandbox server. When I moved over, via a duplicator clone the web service api functionality broke. All requests using the web API return Null (as output by '?')

The local database functionality still works but I need the precision data for my purpose. I checked querying ip locations directly through HTTP and my account works fine.

Any insights would be appreciated

Cheers,
Christopher

**Comment by elialgranti** [comment]
Hi Christopher,

Sorry for the late reply I'm travelling overseas and have been on route for
the better part of the last 48 hours.
The plugin is just a slim layer over MaxMind's library. The only difference
between local db and web service is that one uses the local db reader from
the library and the other the network reader.
I have not looked at the library code so I can just guess at the source of
the problem.
The first step would be to enable debug mode in wordpress and see whether
there is an error message with more information.
It is likely the problem is a network/firewall issue with your production
server. You can confirm this by remote login (ssh or the like) to your
production box and opening a tcp connection (telnet or curl) to MaxMind's
web service endpoint ( https://geoip.maxmind.com/geoip/v2.1/city/me).
You don't need to actually query the service just verify that you can
connect to it.
Hope this helps.

Eli
